### ISSUE TITLE
types not populating on objects instantiated from the data structures

### ISSUE THREAD

**Issue by jasekiw** [basarat/typescript-collections#42]
I import the library using:

`import * as Collections from "typescript-collections";`

I then instantiate it:
`var test = new Collections.Dictionary<string,number>();`

but when I try to access properties using 

`test.propertyHere`

The ide does not pick up the type. It shows no methods or properties for the object.

my tsconfig is as follows:

```
{
  "compilerOptions": {
    "module": "amd",
    "target": "es5",
    "sourceMap": true,
    "moduleResolution": "node"
  },
  "exclude": [
    "node_modules",
    "../typings"
  ]
}
```

I am using this in the browser with requirejs. It also does not seem to find the module with requirejs but I think that is another problem.

**Comment by episage** [comment]
Hi @jasekiw , thanks for using `typescript-collections`. 
Please switch to Visual Studio Code. It's open source and will pick up typings. 
Also, if you exclude `../typings` it naturally won't autocomplete because you excluded the typings.

If you are using this in a browser please switch to IDE such as Visual Studio Code. It has quite decent debugging capabilities. Keep in mind that you will need to generate `*.map` files for your project to debug TypeScript in the browser.

**Comment by jasekiw** [comment]
I am not going to be able to switch IDE's. I have too much rooted into this IDE. We are using it at work and it is a very good IDE. I'm doing something strange with excluding the typings so please ignore that. Other node modules that I have included work fine with typescript in the editor. It just seems to be this library. Then again other node modules have used typings and it works fine. the difference I believe is that express uses the typings module to install typings. typings seems to becoming the standard for installing typings for node modules. Perhaps making a typings repository for it may fix the problem. I could try and make it if you are busy with other bugs because it would probably take some time to build.

**Comment by jasekiw** [comment]
I found the issue. 

`export { default as Dictionary } from './Dictionary';`

apparently the editor doesn't like the default export renamed.
I will post this as a bug to jetbrains

**Comment by episage** [comment]
Thank's 👍
